### ISSUE TITLE
Help: which probability to chose in y_pred segment

### ISSUE THREAD

**Issue by changgunyee** [kyungyunlee/ismir2018-revisiting-svd#7]
I want to use this for my voice detection(RNN-VD).

But i don't know what y_pred means.

I know y_pred is (segment,RNN_INPUT_SIZE,1), but in one segment there's RNN_INPUT_SIZE probabilities and i don't know which to choose.

can you help?

**Comment by changgunyee** [comment]
I misunderstood code. sorry...

**Comment by kyungyunlee** [comment]
I think I have answered your question over email :)
